[package]

name = "glutin"
version = "0.0.10"
authors = ["tomaka <pierre.krieger1708@gmail.com>"]
description = "Cross-plaform OpenGL context provider. Important: the crates.io only supports Windows and Linux for the moment."
keywords = ["windowing", "opengl"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/tomaka/glutin"
documentation = "http://tomaka.github.io/glutin/"
build = "build.rs"

[features]
default = ["window"]
window = []
headless = []

[dependencies]
gl_common = "*"
libc = "*"

[build-dependencies]
gl_generator = "*"
khronos_api = "*"

[dev-dependencies]
clock_ticks = "*"

[target.arm-linux-androideabi.dependencies.android_glue]
git = "https://github.com/skligys/android-rs-glue"

[target.i686-apple-darwin.dependencies.glutin_cocoa]
version = "0"

[target.x86_64-apple-darwin.dependencies.glutin_cocoa]
version = "0"

[target.i686-apple-darwin.dependencies.glutin_core_graphics]
version = "0"

[target.x86_64-apple-darwin.dependencies.glutin_core_graphics]
version = "0"

[target.i686-apple-darwin.dependencies.core_foundation]
version = "0"

[target.x86_64-apple-darwin.dependencies.core_foundation]
version = "0"

[target.i686-pc-windows-gnu.dependencies]
winapi = "0.1"
gdi32-sys = "*"
user32-sys = "*"
kernel32-sys = "*"

[target.x86_64-pc-windows-gnu.dependencies]
winapi = "0.1"
gdi32-sys = "*"
user32-sys = "*"
kernel32-sys = "*"
